// Package kclgen generates a KCL schema package from Bento's configuration
// spec tree. The output is intended to be written to a `.k` file and used
// as the authoring surface for KCL-based Bento config files, which are then
// rendered to YAML via `kcl run` and fed to `bento -c`.
//
// Unlike CUE, KCL has no general disjunction type for free-form config
// authoring. Component families are therefore emitted as a single union
// schema with one optional attribute per component, backed by a dedicated
// per-component schema. See internal/kclgen/component.go for details and
// website/docs/configuration/using_kcl.md for author-side guidance.
package kclgen

import (
	"fmt"
	"strings"

	"github.com/warpstreamlabs/bento/internal/config/schema"
)

// GenerateSchema produces KCL source describing the full Bento config
// surface. The returned bytes form a self-contained `.k` file.
func GenerateSchema(sch schema.Full) ([]byte, error) {
	w := newWriter()

	w.line("# Code generated by bento list --format kcl. DO NOT EDIT.")
	if sch.Version != "" || sch.Date != "" {
		parts := []string{}
		if sch.Version != "" {
			parts = append(parts, "bento "+sch.Version)
		}
		if sch.Date != "" {
			parts = append(parts, "built "+sch.Date)
		}
		w.line("# Generated from " + strings.Join(parts, ", ") + ".")
	}
	w.line("# See https://warpstreamlabs.github.io/bento/docs/configuration/using_kcl for usage.")
	w.blank()

	// Reserve the top-level union and Config schema names up front so
	// nested schemas do not collide with them.
	reserved := map[string]struct{}{}
	for _, n := range []string{
		nameConfigSchema,
		nameInputSchema, nameOutputSchema, nameProcessorSchema,
		nameCacheSchema, nameRateLimitSchema, nameBufferSchema,
		nameMetricSchema, nameTracerSchema, nameScannerSchema,
		nameLabelMixin, nameProcessorsMixin,
		nameInputProtocol, nameOutputProtocol, nameProcessorProtocol,
		nameCacheProtocol, nameRateLimitProtocol, nameBufferProtocol,
		nameMetricProtocol, nameTracerProtocol, nameScannerProtocol,
	} {
		reserved[n] = struct{}{}
		w.used[n] = struct{}{}
	}

	// Pre-pass: collect enumerated-string option sets that appear in
	// multiple fields and promote them to top-level `type` aliases.
	// This lets a single `Codec` alias back a dozen codec fields rather
	// than repeating a 16-value union at each use-site.
	w.typeAliases = collectTypeAliases(sch, reserved)
	for _, a := range w.typeAliases {
		w.used[a.name] = struct{}{}
	}
	writeTypeAliases(w, w.typeAliases)

	// Shared mixins used by category schemas that expose `label` and/or
	// `processors`. Declaring them once avoids repeating the attributes
	// on every category schema.
	writeMixins(w)

	// Top-level Config schema.
	w.blank()
	w.line("schema " + nameConfigSchema + ":")
	w.indent++
	if err := w.writeFieldSpecs(nameConfigSchema, sch.Config); err != nil {
		return nil, fmt.Errorf("config: %w", err)
	}
	w.indent--

	// Drain any nested schemas produced while rendering the Config body.
	if err := w.flushPending(); err != nil {
		return nil, err
	}

	if err := w.writeComponents(sch.Inputs, componentKind{
		unionSchema:        nameInputSchema,
		componentSuffix:    "Input",
		canLabel:           true,
		canPreProcess:      true,
		requiresExactlyOne: true,
		noun:               "input",
	}); err != nil {
		return nil, fmt.Errorf("inputs: %w", err)
	}
	if err := w.writeComponents(sch.Outputs, componentKind{
		unionSchema:        nameOutputSchema,
		componentSuffix:    "Output",
		canLabel:           true,
		canPreProcess:      true,
		requiresExactlyOne: true,
		noun:               "output",
	}); err != nil {
		return nil, fmt.Errorf("outputs: %w", err)
	}
	if err := w.writeComponents(sch.Processors, componentKind{
		unionSchema:        nameProcessorSchema,
		componentSuffix:    "Processor",
		canLabel:           true,
		requiresExactlyOne: true,
		noun:               "processor",
	}); err != nil {
		return nil, fmt.Errorf("processors: %w", err)
	}
	if err := w.writeComponents(sch.Caches, componentKind{
		unionSchema:        nameCacheSchema,
		componentSuffix:    "Cache",
		canLabel:           true,
		requiresExactlyOne: true,
		noun:               "cache",
	}); err != nil {
		return nil, fmt.Errorf("caches: %w", err)
	}
	if err := w.writeComponents(sch.RateLimits, componentKind{
		unionSchema:        nameRateLimitSchema,
		componentSuffix:    "RateLimit",
		canLabel:           true,
		requiresExactlyOne: true,
		noun:               "rate_limit",
	}); err != nil {
		return nil, fmt.Errorf("rate limits: %w", err)
	}
	if err := w.writeComponents(sch.Buffers, componentKind{
		unionSchema:     nameBufferSchema,
		componentSuffix: "Buffer",
		noun:            "buffer",
	}); err != nil {
		return nil, fmt.Errorf("buffers: %w", err)
	}
	if err := w.writeComponents(sch.Metrics, componentKind{
		unionSchema:     nameMetricSchema,
		componentSuffix: "Metric",
		noun:            "metrics",
	}); err != nil {
		return nil, fmt.Errorf("metrics: %w", err)
	}
	if err := w.writeComponents(sch.Tracers, componentKind{
		unionSchema:     nameTracerSchema,
		componentSuffix: "Tracer",
		noun:            "tracer",
	}); err != nil {
		return nil, fmt.Errorf("tracers: %w", err)
	}
	if err := w.writeComponents(sch.Scanners, componentKind{
		unionSchema:        nameScannerSchema,
		componentSuffix:    "Scanner",
		requiresExactlyOne: true,
		noun:               "scanner",
	}); err != nil {
		return nil, fmt.Errorf("scanners: %w", err)
	}

	writeProtocols(w)

	return []byte(w.String()), nil
}

// writeMixins emits the shared mixin schemas used by category union schemas
// to compose their `label` and `processors` attributes. In KCL a mixin is
// conventionally a schema whose name ends with `Mixin`; host schemas
// include it via `mixin [Name]`.
func writeMixins(w *writer) {
	w.line("schema " + nameLabelMixin + ":")
	w.indent++
	w.line(`r"""An optional label for the component, used when referencing it from other parts of the config."""`)
	w.line("label?: str")
	w.indent--

	w.blank()
	w.line("schema " + nameProcessorsMixin + ":")
	w.indent++
	w.line(`r"""An optional list of processors executed on each message after the component processes it."""`)
	w.line("processors?: [" + nameProcessorSchema + "]")
	w.indent--
}

// writeProtocols emits one protocol per component category. Protocols are
// included as an ergonomic aid for user-written helpers that want to
// annotate parameters with a category contract. Note that KCL protocols
// cannot be implemented via inheritance outside of schema mixins, so the
// per-category schemas above do not declare themselves as implementing the
// matching protocol; the protocols remain useful as documentation and as
// structural type annotations on free-standing variables and parameters.
//
// Protocols may not reference concrete schemas in their attribute types,
// only other protocols. Consequently the `processors` attribute on
// `InputLike` / `OutputLike` is typed as `[ProcessorLike]` rather than
// `[Processor]`, and `ProcessorLike` is emitted first.
func writeProtocols(w *writer) {
	type proto struct {
		name         string
		doc          string
		hasProcessor bool
	}
	protocols := []proto{
		// ProcessorLike must appear first so the input/output protocols
		// can reference it.
		{nameProcessorProtocol, "Structural contract for Bento processor components.", false},
		{nameInputProtocol, "Structural contract for Bento input components.", true},
		{nameOutputProtocol, "Structural contract for Bento output components.", true},
		{nameCacheProtocol, "Structural contract for Bento cache components.", false},
		{nameRateLimitProtocol, "Structural contract for Bento rate-limit components.", false},
		{nameScannerProtocol, "Structural contract for Bento scanner components.", false},
		{nameBufferProtocol, "Structural contract for Bento buffer components.", false},
		{nameMetricProtocol, "Structural contract for Bento metric components.", false},
		{nameTracerProtocol, "Structural contract for Bento tracer components.", false},
	}
	for _, p := range protocols {
		w.blank()
		w.line("protocol " + p.name + ":")
		w.indent++
		w.line(`r"""` + p.doc + `"""`)
		w.line("label?: str")
		if p.hasProcessor {
			w.line("processors?: [" + nameProcessorProtocol + "]")
		}
		w.indent--
	}
}
